### ISSUE TITLE
can't install on ubuntu (miniconda/conda-forge)

### ISSUE THREAD

**Issue by tdcwilliams** [nansencenter/py-thesaurus-interface#14] opened 2018-01-03 10:34 UTC
When I do the command
pip install https://github.com/nansencenter/py-thesaurus-interface/archive/master.tar.gz

I get the error:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-MVU4Zj-build/setup.py", line 84, in <module>
        cmdclass = {'install_scripts': update_vocabularies}
      File "/home/timill/Packages/python/miniconda2-conda-forge/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/home/timill/Packages/python/miniconda2-conda-forge/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/home/timill/Packages/python/miniconda2-conda-forge/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/home/timill/Packages/python/miniconda2-conda-forge/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/timill/Packages/python/miniconda2-conda-forge/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/timill/Packages/python/miniconda2-conda-forge/lib/python2.7/distutils/command/install.py", line 575, in run
        self.run_command(cmd_name)
      File "/home/timill/Packages/python/miniconda2-conda-forge/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/home/timill/Packages/python/miniconda2-conda-forge/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-MVU4Zj-build/setup.py", line 31, in run
        import pythesint as pti
      File "pythesint/__init__.py", line 2, in <module>
        from pythesint.pythesint import update_all_vocabularies
      File "pythesint/pythesint.py", line 39, in <module>
        _process_config()
      File "pythesint/pythesint.py", line 24, in _process_config
        fromlist=[__name__])
      File "pythesint/wkv_vocabulary.py", line 6, in <module>
        from pythesint.json_vocabulary import JSONVocabulary
      File "pythesint/json_vocabulary.py", line 7, in <module>
        from pythesint.pathsolver import DATA_HOME
      File "pythesint/pathsolver.py", line 5, in <module>
        from xdg import (XDG_DATA_HOME)
      File "/home/timill/Packages/python/miniconda2-conda-forge/lib/python2.7/site-packages/xdg.py", line 40
        def _getenv(variable: str, default: str) -> str:
                            ^
    SyntaxError: invalid syntax

**Comment by aleksandervines** [comment] 2018-01-05 14:47
I expect this to be a duplicate of #13 - just with a slightly different look due to using different python installations.

**Closed by aleksandervines** 2018-01-05 14:47 UTC
Labels: duplicate
